version: '3'

services:
  redis:
    ports:
      - "6379:6379"
    image: "redis:alpine"

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
