default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: turbo_chatroom_admin_dev
  username: postgres
  password: postgres